#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DATA_DIR}"
mkdir -p "${APP_DIR}/postgres"

# Generate secrets file if it doesn't exist
SECRETS_FILE="${APP_DIR}/.secrets"
if [ ! -f "${SECRETS_FILE}" ]; then
  cat > "${SECRETS_FILE}" <<EOF
# Auto-generated secrets for Monero Merchant
DB_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
JWT_REFRESH_SECRET=$(openssl rand -hex 32)
JWT_MONEROPAY_SECRET=$(openssl rand -hex 32)
JWT_LWS_TOKEN=$(openssl rand -hex 32)
WALLET_PASSWORD=$(openssl rand -hex 16)
EOF
  chmod 600 "${SECRETS_FILE}"
fi

# Source secrets for use in .env generation
export $(grep -v '^#' "${SECRETS_FILE}" | xargs)

# Build daemon RPC endpoint from user-configured hostname/port
DAEMON_HOST="${APP_MONERO_DAEMON_RPC_HOSTNAME:-host.docker.internal}"
DAEMON_PORT="${APP_MONERO_DAEMON_RPC_PORT:-18089}"
DAEMON_ENDPOINT="http://${DAEMON_HOST}:${DAEMON_PORT}/json_rpc"

# Write .env for the backend and postgres
ENV_FILE="${APP_DIR}/.env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by exports.sh — do not edit manually
ADMIN_NAME=admin
ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
PORT=8080

DB_HOST=db
DB_USER=moneromerchant
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=moneromerchant
DB_PORT=5432

JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_MONEROPAY_SECRET=${JWT_MONEROPAY_SECRET}
JWT_LWS_TOKEN=${JWT_LWS_TOKEN}

MONEROPAY_BASE_URL=${APP_MONEROPAY_BASE_URL:-http://host.docker.internal:5000}
MONEROPAY_CALLBACK_URL=${APP_MONEROPAY_CALLBACK_URL:-http://monero-merchant_backend_1:8080/callback/}

MONERO_DAEMON_RPC_ENDPOINT=${DAEMON_ENDPOINT}
MONERO_DAEMON_RPC_HOSTNAME=${DAEMON_HOST}
MONERO_DAEMON_RPC_PORT=${DAEMON_PORT}
MONERO_DAEMON_RPC_USERNAME=${APP_MONERO_DAEMON_RPC_USERNAME}
MONERO_DAEMON_RPC_PASSWORD=${APP_MONERO_DAEMON_RPC_PASSWORD}

MONERO_WALLET_RPC_ENDPOINT=${APP_MONERO_WALLET_RPC_ENDPOINT:-http://host.docker.internal:18083/json_rpc}
MONERO_WALLET_RPC_USERNAME=${APP_MONERO_WALLET_RPC_USERNAME}
MONERO_WALLET_RPC_PASSWORD=${APP_MONERO_WALLET_RPC_PASSWORD}

WALLET_NAME=wallet
WALLET_PASSWORD=${WALLET_PASSWORD}
WALLET_AUTO_REFRESH_PERIOD=2
EOF

chmod 600 "${ENV_FILE}"
