package com.moneromerchant.pos.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDark = Color(0xFFF26722)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF0E0B1D)
val onPrimaryContainerDark = Color(0xFF0E0B1D)
val secondaryDark = Color(0xFF181623)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFF2A2738)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFFF0000)
val onTertiaryDark = Color(0xFFFF0000)
val tertiaryContainerDark = Color(0xFFFF0000)
val onTertiaryContainerDark = Color(0xFFFF0000)
val errorDark = Color(0xFFFF0000)
val onErrorDark = Color(0xFFFF0000)
val errorContainerDark = Color(0xFFFF0000)
val onErrorContainerDark = Color(0xFFFF0000)
val backgroundDark = Color(0xFF0E0B1D)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF181623)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF232031)
val onSurfaceVariantDark = Color(0xFFFFFFFF)
val outlineDark =Color(0xFFFF0000)
val outlineVariantDark = Color(0x1AFFFFFF)
val scrimDark = Color(0xFFFF0000)
val inverseSurfaceDark = Color(0xFFFF0000)
val inverseOnSurfaceDark = Color(0xFFFF0000)
val inversePrimaryDark = Color(0xFFFF0000)
val surfaceDimDark = Color(0xFFFF0000)
val surfaceBrightDark = Color(0xFFFF0000)
val surfaceContainerLowestDark = Color(0xFFFF0000)
val surfaceContainerLowDark = Color(0xFFFF0000)
val surfaceContainerDark = Color(0xFFFF0000)
val surfaceContainerHighDark = Color(0xFFFFFFFF)
val surfaceContainerHighestDark = Color(0xFFFF0000)
